export const CONTACT_LIST = 'Contacts'
export const CONTACT_DETAILS = 'Contact Details'
export const CREATE_CONTACTS = 'Create Contact'
export const SETTINGS = 'Settings '
export const LOGIN = 'Login'
export const REGISTER = 'Register'
export const HOME_NAVIGATOR='Sampark'
